# Define nossa imagem base
FROM jenkins/jenkins:lts-jdk11

# Define nosso usuario dentro do container
USER root

# Executa comandos para instalar o maven
RUN apt-get update

RUN apt-get install -y wget

RUN wget --no-verbose -O /tmp/apache-maven-3.9.1-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz

RUN tar xzf /tmp/apache-maven-3.9.1-bin.tar.gz -C /opt/
RUN ln -s /opt/apache-maven-3.9.1 /opt/maven
RUN ln -s /opt/maven/bin/mvn /usr/local/bin
RUN rm -f /tmp/apache-maven-3.9.1-bin.tar.gz

# Define uma variavel de ambiente MAVEN_HOME que aponta para o local do maven
ENV MAVEN_HOME /opt/maven

# chown: comando linux que muda o dono de uma pasta. Nesse caso estamos dando permissao para o usuario jenkins
RUN chown -R jenkins:jenkins /opt/maven

# Instalando mailutils
RUN apt-get install -y mailutils

# Limpa arquivos baixados com apt-get
RUN apt-get clean

USER jenkins